<?php

abstract class TestCase extends Laravel\Lumen\Testing\TestCase
{
    /**
     * Creates the application.
     *
     * @return \Laravel\Lumen\Application
     */
    public function createApplication()
    {
        return require __DIR__.'/../bootstrap/app.php';
    }

    public function disableExceptionHandling(){
         app()->instance(\App\Exceptions\Handler::class, new class extends \App\Exceptions\Handler{
             public function __construct () { }
             public function report ( Exception $exception ) {
                 parent ::report( $exception ); // TODO: Change the autogenerated stub
             }

             public function render($request, Exception $exception)
             {
                 throw $exception;
             }
         });
    }
}
